language: android
# Workaround to get travis to user Android 27: https://github.com/travis-ci/travis-ci/issues/8874
before_install:
- yes | sdkmanager "platforms;android-27"
- yes | sdkmanager "platforms;android-28"

env:
  global:
  - ADB_INSTALL_TIMEOUT=8
  - ANDROID_API=28
  - ANDROID_BUILD_TOOLS=28.0.3

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-google-google_play_services
  - sys-img-x86-google_apis-26

before_script:
- cd project
- echo no | android create avd --force -n test -t android-26 --abi google_apis/x86
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

